import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { renderComparisonMarkdown } from "../case-study-research.ts";
import { artifactsDir } from "../paths.ts";
import { generateTextWithPi } from "../pi-runner.ts";
import { runCodeActAgent, runReactAgent, runSimpleAgent } from "./agents.ts";
import { PiTemporalHarness } from "./pi-harness.ts";
import {
	type HarnessAgentMode,
	type HarnessAgentResult,
	type HarnessDemoOptions,
	type HarnessDemoResult,
	harnessAgentModes,
} from "./types.ts";

export async function runTemporalPiHarnessDemo(
	options: HarnessDemoOptions = {},
): Promise<HarnessDemoResult> {
	const runId = options.runId ?? `pi-temporal-harness-${Date.now()}`;
	const outputDir =
		options.outputDir ?? join(artifactsDir, "harness-runs", runId);
	await mkdir(outputDir, { recursive: true });
	options.onStream?.({
		type: "run-start",
		runId,
		agent: options.agent ?? "all",
	});

	const modes =
		options.agent && options.agent !== "all"
			? [options.agent]
			: [...harnessAgentModes];
	const results = [];
	for (const mode of modes) {
		options.onStream?.({ type: "agent-start", runId, agent: mode });
		const harness = new PiTemporalHarness(
			mode,
			outputDir,
			(event) => {
				options.onStream?.({ ...event, runId });
			},
			{
				researchFetchText: options.researchFetchText,
				researchTargetCount: options.researchTargetCount,
				reactPageBudget: options.reactPageBudget,
				codeActPageBudget: options.codeActPageBudget,
				codeActConcurrency: options.codeActConcurrency,
				llmGenerate: options.llmGenerate,
				enableCodeActTemporalCloud: options.enableCodeActTemporalCloud,
				enableCodeActScaffoldChildWorkflow:
					options.enableCodeActScaffoldChildWorkflow,
				enablePiExtractionCache: options.enablePiExtractionCache,
				piExtractionCachePath: options.piExtractionCachePath,
			},
		);
		switch (mode) {
			case "simple":
				results.push(await runSimpleAgent(harness));
				break;
			case "react":
				results.push(await runReactAgent(harness));
				break;
			case "codeact":
				results.push(await runCodeActAgent(harness));
				break;
		}
		options.onStream?.({
			type: "agent-complete",
			runId,
			result: results[results.length - 1],
		});
	}

	const reportPath = join(outputDir, "pi-temporal-harness-report.md");
	const comparisonPath = await writeComparisonIfAvailable(
		outputDir,
		results,
		options,
	);
	await writeFile(
		reportPath,
		renderReport(runId, results, comparisonPath),
		"utf8",
	);
	const result = { runId, outputDir, reportPath, comparisonPath, results };
	options.onStream?.({ type: "run-complete", runId, result });
	return result;
}

function renderReport(
	runId: string,
	results: HarnessAgentResult[],
	comparisonPath?: string,
): string {
	const lines = [
		"# Pi + Temporal Harness Telemetry",
		"",
		`Run: ${runId}`,
		"",
		"This report is deterministic harness telemetry: prompts, tool calls, validations, artifacts, and state transitions.",
		"The marketing HTML, citations, agent narratives, CodeAct Python scaffold, and ReAct vs CodeAct comparison are generated by Pi/LLM calls and then written by the harness.",
		"",
		"## Agent Ladder",
		"",
		"| Agent | What it demonstrates | Temporal primitives |",
		"| --- | --- | --- |",
		...results.map(
			(result) =>
				`| ${result.title} | ${result.summary} | ${result.temporalPrimitives.join(", ")} |`,
		),
		"",
	];

	for (const result of results) {
		lines.push(`## ${result.title}`, "", result.summary, "", "### Timeline");
		for (const event of result.events) {
			lines.push(
				`- ${event.at} [${event.kind}] ${event.message}${event.artifactPath ? ` -> ${event.artifactPath}` : ""}`,
			);
		}
		if (result.toolCalls.length > 0) {
			lines.push("", "### Tool Calls");
			for (const call of result.toolCalls) {
				lines.push(
					`- ${call.tool}: ${call.input}`,
					"```text",
					call.output,
					"```",
				);
			}
		}
		if (result.workerEvents.length > 0) {
			lines.push("", "### Parallel Worker Events");
			for (const worker of result.workerEvents) {
				lines.push(
					`- ${worker.at} [${worker.workerId}] ${worker.phase}: ${worker.message}${worker.url ? ` (${worker.url})` : ""}`,
				);
			}
		}
		if (result.codeActTemporalCloud) {
			const cloud = result.codeActTemporalCloud;
			lines.push(
				"",
				"### Generated Temporal Cloud Workflow",
				"",
				`- Workflow ID: ${cloud.workflowId || "not started"}`,
				`- Workflow type: ${cloud.workflowType}`,
				`- Task queue: ${cloud.taskQueue}`,
				`- Status: ${cloud.status}`,
				`- Activities: ${cloud.activities.join(", ")}`,
				`- Result: ${cloud.message}`,
			);
		}
		if (result.artifacts.length > 0) {
			lines.push("", "### Artifacts");
			for (const artifact of result.artifacts) {
				lines.push(`- ${artifact.relativePath}: ${artifact.purpose}`);
			}
		}
		lines.push("");
	}

	if (comparisonPath) {
		lines.push(
			"## LLM Comparison Artifact",
			"",
			"The ReAct vs CodeAct comparison was generated by Pi/LLM and exported separately.",
			"",
			`Artifact: ${comparisonPath}`,
		);
	}

	return `${lines.join("\n").trimEnd()}\n`;
}

async function writeComparisonIfAvailable(
	outputDir: string,
	results: HarnessAgentResult[],
	options: HarnessDemoOptions,
): Promise<string | undefined> {
	const react = results.find(
		(result) => result.mode === "react",
	)?.caseStudyResearch;
	const codeact = results.find(
		(result) => result.mode === "codeact",
	)?.caseStudyResearch;
	if (!react || !codeact) return undefined;
	const comparisonPath = join(outputDir, "react-vs-codeact-comparison.md");
	const fallback = renderComparisonMarkdown(react, codeact);
	const prompt = [
		"You are Pi generating a Markdown comparison report for a developer demo.",
		"Compare the LLM-selected ReAct research strategy with CodeAct generated-code research.",
		"Include coverage, elapsed time, failed fetches, retries, extracted records, generated files, final output quality, and exit conditions.",
		"Reference both artifacts: react/react-case-study-page.html and codeact/codeact-case-study-page.html.",
		"Do not expose environment variables, API keys, namespaces, or raw commands.",
		"Use this deterministic comparison as source data, but rewrite it as a polished LLM-generated report:",
		fallback,
	].join("\n");
	const markdown = options.llmGenerate
		? await options.llmGenerate({
				purpose: "react-vs-codeact-comparison-report",
				prompt,
			})
		: await generateTextWithPi({
				prompt,
				skillName: "temporal-codeact-builder",
				timeoutMs: 180_000,
			});
	await writeFile(comparisonPath, `${markdown.trimEnd()}\n`, "utf8");
	return comparisonPath;
}

export function parseHarnessAgent(
	value: string | undefined,
): HarnessAgentMode | "all" {
	if (!value || value === "all") return "all";
	if (harnessAgentModes.includes(value as HarnessAgentMode)) {
		return value as HarnessAgentMode;
	}
	throw new Error(
		`Unknown --agent "${value}". Expected one of: all, ${harnessAgentModes.join(", ")}`,
	);
}
